[package]
name = "d2modman"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "d2modman_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-clipboard-manager = "2"
tauri-plugin-http = "2"
tauri-plugin-shell = "2"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3.11.0"
simd-json = "0.14.3"

# general
bytes = "1.8.0"
futures = "0.3.31"
parking_lot = "0.12.3"
rff = { git = "https://github.com/mpfaff/rff.git" }
tokio = "1.41.1"
uuid = { version = "1.11.0", features = ["serde"] }

# provides gzip
flate2 = "1.0.35"
