[package]
name = "manderrow-wrapper-stage2"
version = "0.1.0"
authors.workspace = true
edition = "2024"

[dependencies]
anyhow = "1.0.94"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
