[package]
name = "manderrow-macros"
version = "0.1.0"
authors.workspace = true
edition = "2024"

[lib]
proc-macro = true

[dependencies]
cruet = "0.15"
quote = "1"
proc-macro2 = "1"
serde_json = "1"
syn = "2"
